### ISSUE TITLE
Trying to verify modified Absol Wish egg

### ISSUE THREAD

**Issue by IngwiePhoenix** [projectpokemon/3rd_Gen_Checker#1]
Hello there!

I commonly use PkHex to edit my pokemon or generate some. Before gen3, this is basically child's play. After, however, it becomes more convoluted. And, making matters worse, adjusting event pokémon is even more troubblesome.

That is how I came across your program: https://projectpokemon.org/home/forums/topic/57863-injecting-gen-iii-event-pokemon-ivs-and-nature-editing/

During the `PID <TID> <SID>` prompt, when I entered the PIDs - both for the original variant stored in PkHex' DB and after I modified it - would just immediately bring me to the "Complete" screen. Even after entering complete garbage.

So, I would like to know if you happen to know anything about modifying the Absol Wish egg to:
- Change the nature to Adamant
- Improve IVs significantly

Thank you very much in advance and kind regards,

Ingwie

**Comment by kamronbatman** [comment]
Sorry for missing your message. This isn't the place to ask how to created hacked Pokemon. Suffice to say, there are only 65535 combinations of IVs for this event. You can easily list them using existing tools and choose which one you want, if a desirable one exists.
